import JsReport from '@jsreport/jsreport-core';
import JsReportHandlebars from '@jsreport/jsreport-handlebars';
import JsReportChromePdf from '@jsreport/jsreport-chrome-pdf';
import type { FarmReportInfo } from '../utils/reportExport.js';

type ReportColumn = { key: string; label: string };
type ReportRow = Record<string, string | number>;

export type JsReportPayload = {
  farm: FarmReportInfo;
  reportTitle: string;
  periodFrom: string;
  periodTo: string;
  generatedAt: string;
  generatedBy?: string;
  columns: ReportColumn[];
  rows: ReportRow[];
  summaryLines?: Array<{ label: string; value: string }>;
};

let reporterPromise: Promise<ReturnType<typeof JsReport>> | null = null;

async function getReporter() {
  if (!reporterPromise) {
    reporterPromise = (async () => {
      const reporter = JsReport({
        // Keep reporting embedded — no studio / separate HTTP port.
        loadConfig: false,
        autoSave: false,
      });
      reporter.use(JsReportHandlebars());
      reporter.use(
        JsReportChromePdf({
          launchOptions: {
            args: ['--no-sandbox', '--disable-setuid-sandbox', '--disable-dev-shm-usage'],
          },
        }),
      );
      await reporter.init();
      return reporter;
    })();
  }
  return reporterPromise;
}

const REPORT_TEMPLATE = `<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8" />
  <style>
    @page { size: A4 portrait; margin: 12mm; }
    body { font-family: Arial, Helvetica, sans-serif; color: #1F2937; font-size: 14px; margin: 0; line-height: 1.4; }
    .brand { color: #008B8B; font-size: 20px; font-weight: 800; margin: 0 0 4px; }
    .title { font-size: 16px; font-weight: 700; margin: 0 0 14px; }
    .meta { width: 100%; border-collapse: collapse; margin-bottom: 16px; font-size: 14px; }
    .meta td { padding: 4px 8px 4px 0; vertical-align: top; font-size: 14px; }
    .meta .label { width: 130px; color: #6B7280; font-weight: 600; }
    .meta .value { font-weight: 700; }
    table.data { width: 100%; border-collapse: collapse; table-layout: fixed; }
    table.data th { background: #008B8B; color: #fff; text-align: left; padding: 8px 6px; font-size: 14px; word-wrap: break-word; }
    table.data td { border-bottom: 1px solid #E5E7EB; padding: 7px 6px; font-size: 14px; word-wrap: break-word; overflow-wrap: anywhere; }
    table.data tr:nth-child(even) td { background: #F8FAFA; }
    .summary { margin-top: 14px; font-size: 14px; }
    .summary-row { display: flex; justify-content: space-between; padding: 4px 0; border-bottom: 1px solid #E5E7EB; font-size: 14px; }
    .footer { margin-top: 20px; color: #6B7280; font-size: 14px; }
  </style>
</head>
<body>
  <p class="brand">Inka Farm Report</p>
  <p class="title">{{reportTitle}}</p>
  <table class="meta">
    <tr><td class="label">Farm</td><td class="value">{{farm.name}}</td></tr>
    <tr><td class="label">Owner</td><td class="value">{{farm.ownerName}}</td></tr>
    {{#if farm.ownerPhone}}<tr><td class="label">Phone</td><td class="value">{{farm.ownerPhone}}</td></tr>{{/if}}
    <tr><td class="label">Location</td><td class="value">{{farm.location}}</td></tr>
    <tr><td class="label">District</td><td class="value">{{farm.district}}</td></tr>
    <tr><td class="label">Sector</td><td class="value">{{farm.sector}}</td></tr>
    <tr><td class="label">Currency</td><td class="value">{{farm.currency}}</td></tr>
    <tr><td class="label">Period</td><td class="value">{{periodFrom}} → {{periodTo}}</td></tr>
    <tr><td class="label">Generated</td><td class="value">{{generatedAt}}</td></tr>
    {{#if generatedBy}}<tr><td class="label">By</td><td class="value">{{generatedBy}}</td></tr>{{/if}}
  </table>

  {{#if summaryLines}}
  <div class="summary">
    {{#each summaryLines}}
    <div class="summary-row"><span>{{label}}</span><strong>{{value}}</strong></div>
    {{/each}}
  </div>
  {{/if}}

  <table class="data">
    <thead>
      <tr>
        {{#each columns}}
        <th>{{label}}</th>
        {{/each}}
      </tr>
    </thead>
    <tbody>
      {{#each rows}}
      <tr>
        {{#each ../columns}}
        <td>{{lookup ../this key}}</td>
        {{/each}}
      </tr>
      {{/each}}
    </tbody>
  </table>
  <p class="footer">Generated by Inka · Confidential farm records</p>
</body>
</html>`;

export async function renderFarmReportPdf(data: JsReportPayload): Promise<Buffer> {
  const reporter = await getReporter();
  const result = await reporter.render({
    template: {
      content: REPORT_TEMPLATE,
      engine: 'handlebars',
      recipe: 'chrome-pdf',
      chrome: {
        landscape: false,
        format: 'A4',
        printBackground: true,
        marginTop: '12mm',
        marginBottom: '12mm',
        marginLeft: '12mm',
        marginRight: '12mm',
      },
    },
    data,
  });
  return Buffer.from(result.content);
}
